import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  keyboardAvoidingView: {
    flex: 1,
    backgroundColor: "#03070D",
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: "center",
    backgroundColor: "#03070D",
  },
  content: {
    width: "100%",
    maxWidth: 402,
    minHeight: 874,
    alignItems: "center",
    paddingHorizontal: 23,
    paddingBottom: 50,
    backgroundColor: "#03070D",
  },
  brand: {
    width: 148,
    height: 92,
    marginTop: 75,
  },
  brandIcon: {
    position: "absolute",
    top: 0,
    left: 37,
    width: 74,
    height: 62,
  },
  brandGame: {
    position: "absolute",
    top: 66,
    left: 0,
    color: "#FFFFFF",
    fontFamily: "OrbitronMedium",
    fontSize: 20,
    fontWeight: "500",
    lineHeight: 25,
    includeFontPadding: false,
  },
  brandControl: {
    position: "absolute",
    top: 66,
    left: 65,
    color: "#E51580",
    fontFamily: "OrbitronMedium",
    fontSize: 20,
    fontWeight: "500",
    lineHeight: 25,
    includeFontPadding: false,
  },
  title: {
    width: "100%",
    marginTop: 32,
    color: "#FFFFFF",
    fontFamily: "OrbitronMedium",
    fontSize: 40,
    fontWeight: "500",
    lineHeight: 50,
    textAlign: "center",
    includeFontPadding: false,
  },
  subtitle: {
    marginTop: 5,
    color: "#6F7783",
    fontFamily: "OrbitronMedium",
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 20,
    textAlign: "center",
    includeFontPadding: false,
  },
  form: {
    width: "100%",
    gap: 20,
    marginTop: 30,
  },
  field: {
    width: "100%",
    height: 69,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#3E4E66",
    borderRadius: 16,
    backgroundColor: "#051124",
  },
  fieldInput: {
    flex: 1,
    height: "100%",
    paddingVertical: 0,
    color: "#FFFFFF",
    fontFamily: "OrbitronMedium",
    fontSize: 16,
    fontWeight: "500",
    textAlignVertical: "center",
  },
  visibilityButton: {
    width: 30,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  forgotPasswordRow: {
    width: "100%",
    alignItems: "flex-end",
    marginTop: 14,
  },
  forgotPasswordText: {
    color: "#00E5FF",
    fontFamily: "OrbitronMedium",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 18,
  },
  submitButton: {
    width: "100%",
    height: 69,
    marginTop: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: "#E51580",
  },
  submitButtonPressed: {
    opacity: 0.82,
  },
  submitButtonDisabled: {
    opacity: 0.65,
  },
  submitButtonText: {
    color: "#FFFFFF",
    fontFamily: "OrbitronMedium",
    fontSize: 26,
    fontWeight: "500",
    lineHeight: 33,
    includeFontPadding: false,
  },
  registerRow: {
    minHeight: 30,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    marginTop: 23,
  },
  registerPrompt: {
    color: "#AAB2C0",
    fontFamily: "OrbitronMedium",
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 20,
  },
  registerLink: {
    minHeight: 30,
    justifyContent: "center",
  },
  registerLinkText: {
    color: "#00E5FF",
    fontFamily: "OrbitronMedium",
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 20,
  },
});
