import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    marginBottom: 30,
    backgroundColor: "inherit",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "inherit",
    marginBottom: 16,
    paddingLeft: 20,
    gap: 12,
  },
  titleGradientBar: {
    width: 4,
    height: 24,
    borderRadius: 2,
  },
  title: {
    fontSize: 18,
    fontWeight: "700",
    color: "#F5F7FF",
    fontFamily: "Orbitron",
    flex: 1,
  },
  viewAll: {
    fontSize: 7,
    color: "#F52E8F",
    fontWeight: "700",
    fontFamily: "Orbitron",
    paddingRight: 20,
  },
  carouselContainer: {
    paddingLeft: 20,
  },
  userCard: {
    marginRight: 8,
    width: 76,
    alignItems: "center",
    gap: 8,
  },
  avatarContainer: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: "#F52E8F",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(245, 46, 143, 0.1)",
  },
  avatar: {
    width: 68,
    height: 68,
    borderRadius: 34,
  },
  userInitial: {
    fontSize: 28,
    fontWeight: "700",
    color: "#F5F7FF",
    fontFamily: "Orbitron",
  },
  avatarGradientContainer: {
    width: 68,
    height: 68,
    borderRadius: 34,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  userInitialOnGradient: {
    fontSize: 28,
    fontWeight: "700",
    color: "#F5F7FF",
    fontFamily: "Orbitron",
    position: "absolute",
  },
  username: {
    fontSize: 8,
    fontWeight: "600",
    color: "#F5F7FF",
    fontFamily: "Orbitron",
    textAlign: "center",
    maxWidth: 76,
    minHeight: 26,
  },
  followButton: {
    backgroundColor: "#F52E8F",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    minWidth: 60,
    alignItems: "center",
    justifyContent: "center",
  },
  followButtonText: {
    fontSize: 8,
    fontWeight: "700",
    color: "#fff",
    fontFamily: "Orbitron",
  },
  loadingContainer: {
    paddingVertical: 40,
    justifyContent: "center",
    alignItems: "center",
  },
});
