import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    marginBottom: 30,
  },
  wrapper: {
    position: 'relative',
  },
  slide: {
    height: 340,
  },
  cardShadow: {
    flex: 1,
    backgroundColor: '#0A0E15',
    shadowColor: '#F52E8F',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.22,
    shadowRadius: 16,
    elevation: 12,
  },
  card: {
    flex: 1,
    overflow: 'hidden',
  },
  image: {
    flex: 1,
  },
  backgroundImage: {
    width: '100%',
    height: '100%',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 50,
    paddingBottom: 18
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginBottom: 12,
  },
  badgeText: {
    fontSize: 8,
    color: '#F5F7FF',
    fontFamily: 'OrbitronBold',
  },
  gameTitle: {
    fontSize: 20,
    lineHeight: 26,
    color: '#F52E8F',
    fontFamily: 'OrbitronBlack',
    marginBottom: 12,
    maxWidth: 322,
    textShadowColor: 'rgba(245, 46, 143, 0.65)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  gameTitleWhite: { /** Primeira linha do titulo 'DESCUBRA NOVOS' */
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
  },
  gameTitleFirstLine: { /** Primeira linha do titulo 'DESCUBRA NOVOS' */
    marginBottom: 0,
  },
  description: {
    fontSize: 10,
    lineHeight: 16,
    color: '#C7CBD1',
    fontFamily: 'OrbitronMedium',
    maxWidth: 285,
    marginBottom: 20,
  },
  ctaButton: {
    width: 150,
    maxWidth: '100%',
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#F52E8F',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  ctaGradient: {
    minHeight: 30,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaText: {
    fontSize: 8,
    color: '#F5F7FF',
    fontFamily: 'OrbitronBold',
  },
  navButton: {
    position: 'absolute',
    top: '50%',
    marginTop: -18,
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: 'rgba(3, 7, 13, 0.68)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  prevButton: {
    left: 10,
  },
  nextButton: {
    right: 10,
  },
  pagination: {
    position: 'absolute',
    bottom: 16,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    zIndex: 2,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(245, 247, 255, 0.5)',
  },
  dotActive: {
    width: 24,
    backgroundColor: '#F52E8F',
    shadowColor: '#F52E8F',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 7,
    elevation: 5,
  },
  loadingContainer: {
    height: 340,
    backgroundColor: '#0A0E15',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
