import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#03070D",
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: "center",
    backgroundColor: "#03070D",
  },
  content: {
    width: "100%",
    maxWidth: 402,
    minHeight: 874,
    alignItems: "center",
    paddingHorizontal: 23,
    paddingBottom: 50,
  },
  brand: {
    width: 148,
    height: 92,
    marginTop: 75,
  },
  brandIcon: {
    position: "absolute",
    top: 0,
    left: 37,
    width: 74,
    height: 62,
  },
  brandGame: {
    position: "absolute",
    top: 66,
    left: 0,
    color: "#FFFFFF",
    fontFamily: "OrbitronMedium",
    fontSize: 20,
    lineHeight: 25,
    includeFontPadding: false,
  },
  brandControl: {
    position: "absolute",
    top: 66,
    left: 65,
    color: "#E51580",
    fontFamily: "OrbitronMedium",
    fontSize: 20,
    lineHeight: 25,
    includeFontPadding: false,
  },
  title: {
    width: "100%",
    marginTop: 32,
    color: "#FFFFFF",
    fontFamily: "OrbitronMedium",
    fontSize: 40,
    lineHeight: 50,
    textAlign: "center",
    includeFontPadding: false,
  },
  subtitle: {
    marginTop: 36,
    marginBottom: 52,
    maxWidth: 320,
    color: "#6F7783",
    fontFamily: "OrbitronMedium",
    fontSize: 16,
    lineHeight: 20,
    textAlign: "center",
  },
  field: {
    width: "100%",
    height: 69,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 45,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#3E4E66",
    borderRadius: 16,
    backgroundColor: "#051124",
  },
  fieldInput: {
    flex: 1,
    height: "100%",
    paddingVertical: 0,
    color: "#FFFFFF",
    fontFamily: "OrbitronMedium",
    fontSize: 16,
  },
  submitButton: {
    width: "100%",
    height: 69,
    marginTop: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: "#E51580",
  },
  backButton: {
    position: "absolute",
    top: 50,
    left: 24,
    zIndex: 10,

    width: 44,
    height: 44,

    alignItems: "center",
    justifyContent: "center"
  },
  submitButtonPressed: {
    opacity: 0.82,
  },
  submitButtonDisabled: {
    opacity: 0.65,
  },
  submitButtonText: {
    color: "#FFFFFF",
    fontFamily: "OrbitronMedium",
    fontSize: 26,
    lineHeight: 33,
  },
  loginRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 25,
  },
  loginPrompt: {
    color: "#AAB2C0",
    fontFamily: "OrbitronMedium",
    fontSize: 16,
  },
  loginLink: {
    color: "#00E5FF",
    fontFamily: "OrbitronMedium",
    fontSize: 16,
  },
});
