import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  card: {
    marginHorizontal: 20,
    marginTop: 16,
    backgroundColor: "#0A0E15",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(0, 229, 255, 0.1)",
    paddingTop: 24,
    paddingBottom: 16,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  settingsButton: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(0, 229, 255, 0.3)",
    backgroundColor: "#03070D",
  },
  avatarWrap: {
    width: 88,
    height: 88,
    borderRadius: 44,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: "#03070D",
    borderWidth: 2,
    borderColor: "rgba(0, 229, 255, 0.45)",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  username: {
    marginTop: 14,
    maxWidth: "80%",
    color: "#F5F7FF",
    fontFamily: "OrbitronBold",
    fontSize: 18,
    fontWeight: "700",
  },
  handle: {
    marginTop: 2,
    color: "#F52E8F",
    fontFamily: "OrbitronMedium",
    fontSize: 10,
  },
  bio: {
    marginTop: 10,
    color: "#CBD2DF",
    fontFamily: "Orbitron",
    fontSize: 11,
    lineHeight: 16,
    textAlign: "center",
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 8,
  },
  locationText: {
    color: "#758096",
    fontFamily: "OrbitronMedium",
    fontSize: 10,
  },
  statsRow: {
    flexDirection: "row",
    alignSelf: "stretch",
    marginTop: 18,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "rgba(0, 229, 255, 0.08)",
  },
  statItem: {
    flex: 1,
    alignItems: "center",
    gap: 2,
  },
  statItemDivider: {
    borderLeftWidth: 1,
    borderLeftColor: "rgba(0, 229, 255, 0.08)",
  },
  statValue: {
    color: "#F5F7FF",
    fontFamily: "OrbitronBold",
    fontSize: 18,
    fontWeight: "700",
  },
  statLabel: {
    color: "#758096",
    fontFamily: "OrbitronMedium",
    fontSize: 9,
  },
});
