import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  card: {
    marginHorizontal: 20,
    marginTop: 14,
    backgroundColor: "#0A0E15",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(0, 229, 255, 0.1)",
    padding: 16,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  headerLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(245, 46, 143, 0.5)",
    backgroundColor: "rgba(245, 46, 143, 0.08)",
  },
  title: {
    color: "#F5F7FF",
    fontFamily: "OrbitronBold",
    fontSize: 14,
    fontWeight: "700",
  },
  subtitle: {
    marginTop: 2,
    color: "#6B7280",
    fontFamily: "OrbitronMedium",
    fontSize: 9,
  },
  newButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(245, 46, 143, 0.6)",
    backgroundColor: "rgba(245, 46, 143, 0.1)",
  },
  newButtonText: {
    color: "#F52E8F",
    fontFamily: "OrbitronBold",
    fontSize: 11,
    fontWeight: "700",
  },

  // Estado vazio
  emptyBox: {
    marginTop: 16,
    alignItems: "center",
    gap: 10,
    paddingVertical: 24,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "rgba(0, 229, 255, 0.15)",
    backgroundColor: "#03070D",
  },
  emptyText: {
    color: "#6B7280",
    fontFamily: "OrbitronMedium",
    fontSize: 12,
    textAlign: "center",
  },

  // Lista
  list: {
    marginTop: 16,
    gap: 10,
  },
  item: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(0, 229, 255, 0.1)",
    backgroundColor: "#03070D",
  },
  itemMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  itemIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(0, 229, 255, 0.2)",
    backgroundColor: "rgba(0, 229, 255, 0.06)",
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    color: "#F5F7FF",
    fontFamily: "OrbitronBold",
    fontSize: 12,
    fontWeight: "700",
  },
  itemDetails: {
    marginTop: 3,
    color: "#758096",
    fontFamily: "OrbitronMedium",
    fontSize: 9,
  },
  openButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(0, 229, 255, 0.25)",
    backgroundColor: "#0A0E15",
  },
  deleteButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(229, 21, 34, 0.4)",
    backgroundColor: "rgba(229, 21, 34, 0.12)",
  },
});
